### ISSUE TITLE
leaflet.markercluster.default not loading

### ISSUE THREAD

**Issue by joshporter1** [scpike/leaflet-markercluster-rails#6]
In the Chrome devtools network tab, I can see that leaflet.markercluster is being loaded, but the other stylesheet is not. This was working before I upgraded a couple of gems (listed below). 

It breaks when I upgraded bootstrap-sass to 3.3.5 and sass-rails to 5.0.0.

It works when I was using sass-rails 4.0.5, which leads me to believe it is the 5.0.0 version of this gem that causes this to break. I'm not sure what it is about this version, but if you have any insight as to why this breaks that would be great. I can provide additional details if necessary.

**Comment by scpike** [comment]
@joshporter1 I haven't done any testing with later versions of bootstrap. If you get it working I'd welcome a pull request  / releasing a new version.

**Comment by tompesman** [comment]
Same here, I've fixed it by switching to this in my scss file:

```scss
@import "leaflet.markercluster";
@import "leaflet.markercluster.default";
```

**Comment by joshporter1** [comment]
That worked like a charm. Thanks!
