### ISSUE TITLE
Would it be possible to update to 0.7?

### ISSUE THREAD

**Issue by bstreiss** [scpike/leaflet-markercluster-rails#7]
Hi,
  I'm wondering if it would be possible (easy?) to update this repo to use leaflet-markercluster 0.7.  As it currently stands the marker icon won't show up (just the number).

**Comment by scpike** [comment]
@bstreiss PR would be welcome, but otherwise I'd encourage you to check out rails-assets. It does this kind of thing in a better way (https://rails-assets.org/#/components/leaflet.markercluster).
